#!/bin/bash

if [[ -z $(which brew) ]];then
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [[ -z $(which pv) ]];then
	brew install -y pv
fi
